import {useEffect,useRef,useState} from 'react';
import gsap from 'gsap';
import {ScrollTrigger} from 'gsap/ScrollTrigger';
import {ArrowDown,ArrowUpRight,X} from 'lucide-react';
import {motion,useReducedMotion} from 'framer-motion';
import {CHAPTERS,ENTRAR} from './config';
import Brand from './components/Brand';
import ProductStage from './components/ProductStage';
import Features from './components/Features';
import Plans from './components/Plans';
gsap.registerPlugin(ScrollTrigger);
export default function App(){
 const story=useRef();const progress=useRef(0);const [chapter,setChapter]=useState(0);const [hotspot,setHotspot]=useState(null);const reduced=useReducedMotion();
 useEffect(()=>{const ctx=gsap.context(()=>{if(reduced)return;gsap.fromTo('.hero-copy',{opacity:0,y:18},{opacity:1,y:0,duration:.9,ease:'power2.out'});gsap.to(progress,{current:1,ease:'none',onUpdate:()=>setChapter(Math.min(CHAPTERS.length-1,Math.floor(progress.current*CHAPTERS.length))),scrollTrigger:{trigger:story.current,start:'top top',end:'bottom bottom',scrub:.7}})},story);return()=>ctx.revert()},[reduced]);
 useEffect(()=>{setHotspot(null)},[chapter]);
 const copy=CHAPTERS[chapter];
 const goChapter=i=>{if(reduced){progress.current=(i+.5)/CHAPTERS.length;setChapter(i);return}const rect=story.current.getBoundingClientRect();window.scrollTo({top:scrollY+rect.top+(story.current.offsetHeight-innerHeight)*((i+.5)/CHAPTERS.length),behavior:'smooth'})};
 return <><a className="skip-link" href="#recursos">Ir para os recursos</a><header className="site-header"><a href="#inicio" aria-label="Forge início"><Brand/></a><nav aria-label="Navegação principal"><a href="#experiencia">Experiência</a><a href="#recursos">O sistema</a><a href="#planos">Planos</a></nav><div className="header-actions"><a href={ENTRAR} className="header-entrar" data-testid="landing-entrar">Entrar</a><a href="#planos" className="header-cta">Conhecer o Forge<ArrowUpRight size={15}/></a></div></header>
 <main><section ref={story} id="inicio" className={`story ${reduced?'reduced':''}`}><div className="story-sticky" id="experiencia"><div className="hero-topline"><span>SEU SISTEMA DE TREINO E ROTINA</span><span>FEITO PARA O SEU DIA A DIA</span></div><div className="hero-copy"><p className="eyebrow"><span/> {copy.tag}</p><h1 key={chapter}>{copy.title.map((line,i)=><span className={i===copy.title.length-1?'last-line':''} key={line}>{line}</span>)}</h1><p className="hero-description">{copy.body}</p><div className="hero-actions"><motion.a whileHover={{y:-2}} whileTap={{scale:.98}} className="cta cta-light" href={chapter===CHAPTERS.length-1?'#planos':'#recursos'}>{copy.label}<ArrowUpRight size={18}/></motion.a>{chapter===0&&<button className="text-button" onClick={()=>goChapter(1)}>Ver por dentro<ArrowDown size={15}/></button>}</div><div className="hero-caption"><span className="caption-line"/>{copy.detail}</div></div><ProductStage progress={progress} chapter={chapter} reduced={reduced} onHotspot={setHotspot}/>
 {hotspot!==null&&<aside className="hotspot-detail" aria-live="polite"><button aria-label="Fechar detalhe" onClick={()=>setHotspot(null)}><X size={16}/></button><span className="eyebrow">0{hotspot+1} / CONECTADO AO SISTEMA</span><h3>{['Treino','Alimentação','Refeições'][hotspot]}</h3><p>{['23 programas completos, 134 exercícios ilustrados e substituições dentro da sua rotina.','29 receitas, substituições alimentares e lista de compras para organizar a semana.','Combinações de refeições e alternativas para escolher dentro da sua rotina.'][hotspot]}</p></aside>}
 <div className="hero-bottom"><div className="chapter-nav" aria-label="Capítulos da experiência">{['Início','Nutrição','Refeições','Preferências','Receitas','Biblioteca','Treino'].map((l,i)=><button aria-pressed={chapter===i} aria-label={l} onClick={()=>goChapter(i)} key={l}><span>0{i+1}</span><i/></button>)}</div><span className="scroll-hint">ROLE PARA DESCOBRIR<ArrowDown size={15}/></span></div></div></section>
 <div className="proof-strip"><span>UMA ROTINA.<br/><b>MAIS POSSIBILIDADES.</b></span><div><strong>23</strong><span>programas completos</span></div><div><strong>134</strong><span>exercícios ilustrados</span></div><div><strong>29</strong><span>receitas para variar</span></div></div>
 <Features/><section className="control-section section-shell"><div className="section-topline"><span>TECNOLOGIA QUE RESPEITA SEU CONTROLE</span><span>FORGE INTELLIGENCE</span></div><div className="control-heading"><h2>Você escolhe<br/>quem conduz.</h2><p>Da primeira recomendação ao seu próprio programa.<br/>O sistema acompanha o seu jeito de organizar.</p></div><div className="control-modes">{[['AUTO','O Forge organiza.','O sistema monta o programa a partir da sua avaliação.'],['ASSISTED','Você aprova.','Receba recomendações e decida o que aplicar.'],['PRO','Você constrói.','Monte o programa ou importe sua ficha por texto.']].map(([name,title,body],i)=><div key={name}><span className="mode-id">0{i+1}<span/>FORGE {name}</span><h3>{title}</h3><p>{body}</p></div>)}</div></section><Plans/>
 <section className="final-cta section-shell"><p className="eyebrow">MENOS DISPERSÃO. MAIS CONTINUIDADE.</p><h2>Sua rotina.<br/><span>Em outro nível.</span></h2><a className="cta cta-orange" href="#planos">Encontre seu Forge<ArrowUpRight size={20}/></a><div className="final-word" aria-hidden="true">FORGE</div></section></main><footer><Brand/><span>Treino. Alimentação. Evolução.</span><a href={ENTRAR} data-testid="rodape-entrar">Já é aluno? Entrar</a><a href="#inicio">Voltar ao início ↑</a></footer><div className="mobile-cta"><span>FORGE OS</span><a href="#planos">Conhecer os planos<ArrowUpRight size={16}/></a></div></>;
}
